language: php

php:
    - 7.3
    - 7.4snapshot
env:
    global:
        SYMFONY_PHPUNIT_VERSION: "8.2"

cache:
    directories:
        - $HOME/.composer/cache/files
        - ./bin/.phpunit

before_install:
    - composer install

script: ./bin/phpunit